services:
  postgres:
    image: postgres:16
    container_name: telecom_map_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256 --auth-local=scram-sha-256'
    ports:
      - '5433:5432'
    volumes:
      - telecom_map_data:/var/lib/postgresql/data
    networks:
      - telecom_map_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: telecom_map_backend
    env_file:
      - .env.local
    ports:
      - '${APP_PORT}:8080'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - telecom_map_network
    volumes:
      - ./backend:/app

volumes:
  telecom_map_data:

networks:
  telecom_map_network:
    driver: bridge
